### ISSUE TITLE
Provide script that can rewrite TS interfaces to object({})

### ISSUE THREAD

**Issue by joshinator** [mojotech/json-type-validation#30]

**Comment by joshinator** [comment]
Hello @mulias ,

Thank you for your detailed answer to my short suggestion :)
Its a very interesting approach. As far as I understand, you would define an object that you can use at runtime and at the same time "extract" its type. I'm just afraid that the types will then not be as easy to read as if you'd just define them in the plain normal way...

I think your library is already good, because you cant really make a mistake when creating the object because its type safe. It just took me super long, that's why I was thinking of a script. The DRY-principle violation is not that bad imho.

Because I think you are forced by the TS-compiler to adjust the object whenever the type changes (also for optional fields)?

**Comment by mulias** [comment]
Now that TS 3.4 has fixed higher order type inference I think that the `Static` should work more consistently. At some point in the future I (or someone reading this) should figure out how to implement `dtslint` for type-level testing and verify that deriving a type from a decoder consistently produces the right result. If that's the case then I think it's appropriate to add the type utility to the library.

That said, I ultimately agree that decoders are harder to read than types, so deriving types off of decoders could lead to confusion.
